source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'rtcGame' do
    pod 'Alamofire', '~> 4.4'
	pod 'AlamofireImage'
	pod 'SwiftyJSON'
	pod "GoogleMaterialIconFont"
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
end
